version: '3.8'

services:
  actual-api:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - DATA_DIR=/data
      - SERVER_URL=${SERVER_URL}
      - SYNC_ID=${SYNC_ID}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./.env:/.env:ro

  actual-api-native:
    build:
      context: .
      dockerfile: Dockerfile.native
    environment:
      - DATA_DIR=/data
      - SERVER_URL=${SERVER_URL}
      - SYNC_ID=${SYNC_ID}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./.env:/.env:ro

